### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-cristinatato#1]
Really cool job @cristinatato  !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the meta title of the page
- [x] Be extra careful with syntax, it looks like you have errors when closing LIs and As, and there is an empty div width class "header__nav"
- [x] Should the `.header__nav` element be a non-semantics `div` or a rich semantic `nav` (commonly used for our main navigation)?
- [x] Menu items should be clickable

## CSS - structure
- [x] Move the font CSS before your main CSS

## CSS - selectors
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color

## CSS - box model
- [x] The main section should fit 100% of the browser's height
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using the box-sizing property to prevent the unwanted vertical scroll

## CSS - other
- [x] Finish the main title styles: words should jump even in a tablet or desktop browser

## Good practices
- [x] Try to improve your commit messages, better in English and using imperative

Let me know if you have any doubts ;)

Go for it!!

**Comment by cristinatato** [comment]
Done ;)

**Comment by oneeyedman** [comment]
Yay! Well done @cristinatato
